###########################################
## Autogenerated by Puppet
## (c) KNAPP AG, 2013
## Author: Franz Pammer
############################################
#
############################################
## !!!WARNING!!!                           #
############################################
## This file is autoamtically generated by #
## Puppet. Any manual changes made to it   #
## **WILL** get overwritten!               #
############################################

# If not running interactively, don't do anything
case $- in
        *i*) ;;
        *) return;;
esac

# Aliase for 'ls'
alias dir='ls -l --color=auto'
alias ls='ls --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -laF --color=auto'

# Coloring 'grep'
GREP_OPTIONS='--color=auto'
GREP_COLOR='1;32'
export GREP_OPTIONS GREP_COLOR

# Coloring 'less'
export LESS='--RAW-CONTROL-CHARS'
